baseURL = "https://caiyouy.github.io/"
languageCode = "zh-cn"
title = "Caiyou Yuan's Pages"
theme = "github-style"
# pygmentsCodeFences = true
# pygmentsUseClasses = true

[params]
  author = "Caiyou Yuan"
  description = "Postdoc at SUSTech"
  github = "caiyouy"
  # facebook = "MeiK2333"
  # twitter = "MeiK2333"
  # linkedin = "MeiK2333"
  # instagram = "MeiK2333"
  # tumblr = "MeiK2333"
  email = "yuancaiyou@hotmail.com"
  url = "https://caiyouy.github.io/"
  # keywords = "blog, google analytics"
  # rss = true
  lastmod = true
  userStatusEmoji = "ðŸ˜Š"
  favicon = "/yuan_cartoon.jpg"
  avatar = "/yuan.png"
  headerIcon = "/yuan_cartoon.jpg"
  location = "China"
  # enableGitalk = true
  custom_css = ["css/custom.css"]
  custom_js = ["js/custom.js"]

  # [[params.links]]
  # title = "Link"
  # href = "https://sustech.edu.cn/"

  # [[params.links]]
  # title = "Link2"
  # href = "https://meik2333.com"
  # icon = "https://meik2333.com/images/avatar.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[services]
  [services.googleAnalytics]
    ID = "UA-123456-789"

